bind = SUPER, q, spawn, kitty --title "kitty $$"
bind = SUPER + SHIFT, E, spawn, element-desktop --password-store=gnome-libsecret
bind = SUPER, R, spawn, fuzzel -w 100 -l 15
bind = SUPER, F, spawn_shell, qutebrowser
bind = SUPER, G, spawn, signal-desktop --password-store=gnome-libsecret

bind=NONE,Print,spawn_shell,slurped=$(slurp) && grim -g "$slurped" - | wl-copy && notify-send "Screenshot of the region taken" -t 1000
bind = SHIFT, print, spawn_shell, grim - | wl-copy && notify-send "Screenshot of whole screen taken" -t 1000 
bind = SUPER, v, spawn_shell, cliphist list | fuzzel --dmenu -w 100 -l 20 | cliphist decode | wl-copy


bind = SUPER + CTRL, r, reload_config
bind = SUPER, c, killclient
bind = SUPER+SHIFT, c, killclient, force
bind = SUPER + SHIFT, f, togglefullscreen

circle_layout=dwindle,monocle
bind = SUPER, m, switch_layout


# media controls 
bind=NONE,XF86MonBrightnessUp,spawn,ddcutil setvcp 10 + 10
bind=SHIFT,XF86MonBrightnessUp,spawn,ddcutil setvcp 10 100
bind=NONE,XF86MonBrightnessDown,spawn,ddcutil setvcp 10 - 10
bind=SHIFT,XF86MonBrightnessDown,spawn,ddcutil setvcp 10 10

bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle


# navigation from cebem1nt
bind = SUPER, 1, view, 1, 0
bind = SUPER, 2, view, 2, 0
bind = SUPER, 3, view, 3, 0
bind = SUPER, 4, view, 4, 0
bind = SUPER, 5, view, 5, 0

bind = SUPER + CTRL, 1, toggleview, 1, 0
bind = SUPER + CTRL, 2, toggleview, 2, 0
bind = SUPER + CTRL, 3, toggleview, 3, 0
bind = SUPER + CTRL, 4, toggleview, 4, 0
bind = SUPER + CTRL, 5, toggleview, 5, 0

bind = SUPER + SHIFT, 1, tag, 1, 0
bind = SUPER + SHIFT, 2, tag, 2, 0
bind = SUPER + SHIFT, 3, tag, 3, 0
bind = SUPER + SHIFT, 4, tag, 4, 0
bind = SUPER + SHIFT, 5, tag, 5, 0

bind = SUPER + SHIFT + CTRL, 1, toggletag, 1
bind = SUPER + SHIFT + CTRL, 2, toggletag, 2
bind = SUPER + SHIFT + CTRL, 3, toggletag, 3
bind = SUPER + SHIFT + CTRL, 4, toggletag, 4
bind = SUPER + SHIFT + CTRL, 5, toggletag, 5

# should work according to docs??
# bind = SUPER, s, toggle_special_tag
# bind = SUPER + SHIFT, s, tag_special_silent

# Move window
bind = SUPER + CTRL, Up,    scroller_stack, up
bind = SUPER + CTRL, Down,  scroller_stack, down
bind = SUPER + CTRL, Left,  scroller_stack, left
bind = SUPER + CTRL, Right, scroller_stack, right
bind = SUPER + CTRL, k,     scroller_stack, up
bind = SUPER + CTRL, j,     scroller_stack, down
bind = SUPER + CTRL, h,     scroller_stack, left
bind = SUPER + CTRL, l,     scroller_stack, right

# swap window
bind = SUPER + SHIFT, Up,    exchange_client, up
bind = SUPER + SHIFT, Down,  exchange_client, down
bind = SUPER + SHIFT, Left,  exchange_client, left
bind = SUPER + SHIFT, Right, exchange_client, right
bind = SUPER + SHIFT, k,     exchange_client, up
bind = SUPER + SHIFT, j,     exchange_client, down
bind = SUPER + SHIFT, h,     exchange_client, left
bind = SUPER + SHIFT, l,     exchange_client, right

# Resize window
bind = SUPER + SHIFT + CTRL, Up,    resizewin,  +0, -50
bind = SUPER + SHIFT + CTRL, Down,  resizewin,  +0, +50
bind = SUPER + SHIFT + CTRL, Left,  resizewin, -50, +0
bind = SUPER + SHIFT + CTRL, Right, resizewin, +50, +0
bind = SUPER + SHIFT + CTRL, k,     resizewin,  +0, -50
bind = SUPER + SHIFT + CTRL, j,     resizewin,  +0, +50
bind = SUPER + SHIFT + CTRL, h,     resizewin, -50, +0
bind = SUPER + SHIFT + CTRL, l,     resizewin, +50, +0

# switch window focus
bind = SUPER, Up,    focus_window_or_workspace, up
bind = SUPER, Down,  focus_window_or_workspace, down
bind = SUPER, Left,  focusdir, left
bind = SUPER, Right, focusdir, right
bind = SUPER, k,     focus_window_or_workspace, up
bind = SUPER, j,     focus_window_or_workspace, down
bind = SUPER, h,     focusdir, left
bind = SUPER, l,     focusdir, right

mousebind = SUPER, btn_left,  moveresize, curmove
mousebind = SUPER, btn_right, moveresize, curresize

