
exec-once = kitty
exec-once = nm-applet
exec-once = dunst
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store


circle_layout=dwindle,grid,tile,master

source = ./binds.conf
source = ./theme.conf
source = ./rules.conf

tag_num = 5

focus_on_activate = 1
sloppyfocus = 1
warpcursor = 1


