tagrule = id:*, layout_name: dwindle

# config tag 5: social
tagrule = id:5, layout_name: fair
windowrule= tags:5, appid:discord
windowrule= tags:5, appid:signal
windowrule= tags:5, appid:slack
windowrule= tags:5, appid:thunderbird



